Install type dependencies for mypy linting
Newer versions of mypy (>=0.900) require external packages for type
information. This commit installs the packages suggested by mypy.

```
commodore/helpers.py:9: error: Library stubs not installed for "requests" (or incompatible with Python 3.9)
commodore/helpers.py:9: note: Hint: "python3 -m pip install types-requests"
commodore/helpers.py:9: note: (or run "mypy --install-types" to install all missing stub packages)
commodore/helpers.py:9: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
commodore/helpers.py:10: error: Library stubs not installed for "yaml" (or incompatible with Python 3.9)
commodore/helpers.py:10: note: Hint: "python3 -m pip install types-PyYAML"
commodore/helpers.py:13: error: Library stubs not installed for "requests.exceptions" (or incompatible with Python 3.9)
```