Install `libmagic1` in Commodore container
This is required for Kapitan 0.31, cf. the following output without
libmagic1 present:

```
$ docker run docker.io/projectsyn/commodore:test
Agent pid 11
grep: /app/.ssh: No such file or directory
No SSH keys were added
Traceback (most recent call last):
  File "/usr/local/bin/commodore", line 5, in <module>
    from commodore.cli import main
  File "/usr/local/lib/python3.11/site-packages/commodore/cli/__init__.py", line 13, in <module>
    from .catalog import catalog_group
  File "/usr/local/lib/python3.11/site-packages/commodore/cli/catalog.py", line 4, in <module>
    from commodore.catalog import catalog_list, Migration
  File "/usr/local/lib/python3.11/site-packages/commodore/catalog.py", line 17, in <module>
    from .helpers import (
  File "/usr/local/lib/python3.11/site-packages/commodore/helpers.py", line 20, in <module>
    from kapitan import targets as kapitan_targets
  File "/usr/local/lib/python3.11/site-packages/kapitan/targets.py", line 25, in <module>
    from kapitan.dependency_manager.base import fetch_dependencies
  File "/usr/local/lib/python3.11/site-packages/kapitan/dependency_manager/base.py", line 19, in <module>
    from kapitan.utils import (
  File "/usr/local/lib/python3.11/site-packages/kapitan/utils.py", line 12, in <module>
    import magic
  File "/usr/local/lib/python3.11/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```