Add missing `Optional` to function arguments with default value `None`
Mypy has started to emit the following error for arguments with default
values which don't match the argument's type annotation:

```
error: Incompatible default for argument "cloud" (default has type "None", argument has type "str")  [assignment]
note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
```

This commit fixes all occurrences of this new error in the Commodore
code base.