Remove Python 3.9.7 from test matrix
GitHub doesn't provide Python 3.9.7 out of the box anymore, the action
errors with:

```
Version 3.9.7 was not found in the local cache
Error: Version 3.9.7 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

The effort to install a custom Python version outweighs the benefit we
get from keeping 3.9.7 in the test matrix by a large margin, so we're
just removing 3.9.7.